#  ------------ System parameters ------------

BATTERY_CAPACITY = 10.0 #KWH
INITIAL_SOC = 5.0 #KWH
MIN_SOC = 0 #KWH
MAX_CHARGE_RATE = 3.0 #KW
MAX_DISCHARGE_RATE = 3 #KW
EFFICIENTY = 0.9
EXPORT_PRICE = 3 # $/KWH
MAX_EXPORT = 10  #KWH
CYCLE_COST_PER_KWH = 0.1
DAYS = 60
TOTAL_HOURS = 24 * DAYS